### PR TITLE
Updating the plugin to OpenSearch 2.0 and Querqy-Lucene 5.4

### PR DESCRIPTION
**Pull request by ps48**
Upgrades include:

1. OpenSearch bump to 2.0
2. Querqy-Lucene 5.4
3. Gradle 7.4.2
4. Updated CI workflow to match OpenSearch Core and Java versions

**NOTE:** I see 3 test failures, @JohannesDaniel @renekrie might need some help with these. 
 ~~- querqy.opensearch.RewriterShardContextsTest.testClearRewritersFromCache -> Seems to be flaky~~
 ~~- querqy.opensearch.rewriter.WordBreakCompoundRewriterFactoryTest.testCreateRewriter -> Maybe related to #11~~ 
 ~~- querqy.opensearch.rewriter.WordBreakCompoundRewriterFactoryTest.testThatDefaultConfigurationIsApplied -> Maybe related to upstream querqy changes~~

Issues resolved: #16, #15  
- [x] **Update Gradle to version 7**
- [x] **Add upstream changes from OpenSearch 2.0**
- [x] **Add upstream changes from Querqy -Lucene 9**
- [x] **Update tests**
- [x] **Check tests and build**

### CODE REVIEW

**Comment by renekrie** [comment]
"querqy.opensearch.RewriterShardContextsTest.testClearRewritersFromCache -> Seems to be flaky" - I'm seeing the same under ES. It seems that in some cases, the test frame work does not go through the process of creating the `querqy` query to the Querqy plugin but reuses the Querqy query object that is put together in the test. As a result, the request processor does not get injected into query object, which finally results in an NPE.

Let me push my branch to querqy-elasticsearch, maybe this will show a solution for some of the other issues.

**Comment by renekrie** [comment]
I converted this into a draft PR so that we don't merge it accidentally

**Comment by renekrie** [comment]
I finally found a fix for the flaky RewriterShardsContextsTest in the query-elasticsearch version: https://github.com/querqy/querqy-elasticsearch/pull/23/files#diff-3d9c183f14569b387180b9b3b4c237991c4ff47113d3f345fe5d41bacc2af7b0

The problem is that the test framework seems to re-use the QuerqyQueryBuilder object in case the request goes to the 'local node' instead of fully processing a request and creating a new QuerqyQueryBuilder object. In that case, the QuerqyPlugin is not invoked and cannot inject a QuerqyProcessor object, which leads to an NPE. As the nodes are picked randomly by the test framework, the test doesn't always fail.
Solution: I pick the first node to send the query to and then route the query to the other nodes via search request preferences.
I have to say that this was a bit trial and error as this is very hard to debug because of the underlying asynchronous request handling - so I'm not 100% sure of my workaround but I haven't seen a test failure for quite a bit.
@ps48 Would you have the capacity to port this to this PR?

**Comment by ps48** [comment]
@renekrie Sure I'll take this up, sorry for the delay. Missed the above comment.

**Comment by ps48** [comment]
Ported changes for RewriterShardsContext and WordbreakRewriter. All tests pass for the local build

**Review by renekrie — APPROVED** [review]
Thank you @ps48

**Pull request merged**
